### ISSUE TITLE
Produce cheat sheet summarising the learning

### ISSUE THREAD

**Issue by ChrisBeeley** [nhs-r-community/shiny-training#2]
Have a downloadable cheat sheet in the repo that shows a summary of all of the functions and learning from the program that people can refer to

**Comment by MarkMc1089** [comment]
Hi, I am quite new to both the NHS and R, but should be able to compile a cheat sheet for this. Would it be best in PDF form? I can use RMarkdown for the practice :)

**Comment by ChrisBeeley** [comment]
Great, thanks! If you're doing RMarkdown pdf and HTML would be good (HTML for accessibility).

Thanks again!

**Comment by MarkMc1089** [comment]
Hi Chris, I managed to make a start finally: https://github.com/MarkMc1089/shiny-training/tree/write_cheat_sheet

It is just outputting html for now, and only covering intro_1 slides so far. Is this kind of what you were expecting?

**Comment by ChrisBeeley** [comment]
Looks good to me, thanks!

**Comment by MarkMc1089** [comment]
I added a much shorter version, which is best to continue with? Just thinking if I continue along the lines of the original one, it might turn into a cheat novella, rather than a sheet!

**Comment by ChrisBeeley** [comment]
Thanks, I've made a PR with a few edits, looks good to me though (feel free to ignore edits! :slightly_smiling_face: )

**Comment by MarkMc1089** [comment]
Thanks Chris, I used your edits with just a slight modification over headings. I've added the intro_2 contents into the cheat sheet. One issue you may be able to help me with - how to get the shiny app output as a picture to include in the static outputs? So far it is just the section for Layouts that this is needed for.

**Comment by ChrisBeeley** [comment]
![Screenshot from 2021-12-21 15-55-48](https://user-images.githubusercontent.com/1259867/146960485-fab8679a-b60e-40cb-883c-662cbbaafe41.png)

Screenshot?

**Comment by MarkMc1089** [comment]
Hi @ChrisBeeley - I've finished the cheat sheet. Once you have had a look thru just let me know if there are any changes required. I will tidy up the presentation of the PDF (probably just adding some pagebreaks where needed) once the content is fully completed.

I didn't quite get automatic rendering of a Shiny app into PDF, but came up with an easily repeatable solution using the `shinyscreenshot` package :)

**Comment by ChrisBeeley** [comment]
I'm so sorry, I forgot about this PR. I've been rather sick and I was in hospital recently.

I'll look this week, thanks for your time and sorry I've been so slow

**Comment by ChrisBeeley** [comment]
I've had a look now. Looks all good to me, thanks, please submit and we'll get it merged in :rocket:

**Comment by ChrisBeeley** [comment]
Sorry, this slipped off my radar. Could you make a PR against the repo please and we'll merge it in? :pray:
