### ISSUE TITLE
activate renv

### ISSUE THREAD

**Issue by CorradoLanera** [nhs-r-community/shiny-training#5]
Hi all, 
I am looking forward to the course this evening.

Reading the README, I would ask if the project could benefit (in terms of friction in the installation phase from students) from activating renv. I am undecided what is better between a list of installation steps for setup or a new tool (from students' point of view, i.e., renv) to adopt that is _not related_ to the content of the course.

**Comment by ChrisBeeley** [comment]
That is a great point, thanks for filing an issue! I confess, I have never used renv, but it probably would benefit from this approach.

If you'd be happy to send me any further thoughts (or even a PR 😁) I would be very grateful. If not I will investigate myself some time.

Thanks! 🙏

**Comment by ChrisBeeley** [comment]
Closed by #7
